version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5004:5004"
    environment:
      - FLASK_APP=app.py
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: .  # Set context to root directory
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env  # Include the environment variables file here
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge