services:
  # Backend Service (Flask)
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    plan: free  # Adjust as necessary based on your plan with Render
    envVars:
      - key: FLASK_APP
        value: app.py
    ports:
      - port: 5004  # Expose the Flask app on port 5004

  # Frontend Service (React)
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
    plan: free  # Adjust as necessary based on your plan with Render
    envVars:
      - key: NODE_ENV
        value: production
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    ports:
      - port: 3000  # Expose the React app on port 3000
    envVarsFilePath: .env  # Reference to your .env file with environment variables
    dependsOn:
      - backend
